spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.security: DEBUG

springdoc:

  swagger-ui:
    path: /bezkoder-documentation
  api-docs:
    path: /bezkoder-api-docs

    tryItOutEnabled: true
    filter: true

bezkoder:
  openapi:
    dev-url: http://localhost:8081
    prod-url: http://168.119.132.18:8080

  app:
    jwtCookieName: bezkoder
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000

schemes:
  - https

server:
  port: 8081

# http://localhost:8081/swagger-ui/index.html#
