spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: root
    password: root
#  messages:
#    basename: messages
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true

  #spring:
#  datasource:
#    url: jdbc:mysql://node6720-spring-boot-app2.fin.libyanspider.cloud/Booking
#    username: root
#    password: VSInnl48944
#    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    url: jdbc:mysql://168.119.132.15:3306/Booking
#    username: root
#    password: VSInnl48944
#    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.springframework.security: DEBUG

#springdoc:
#  api-docs:
#    enabled: false
#  swagger-ui:
#    enabled: false
#  packages-to-scan: com.bezkoder.spring.swagger.controller
springdoc:

  swagger-ui:
    path: /bezkoder-documentation
  api-docs:
    path: /bezkoder-api-docs

    tryItOutEnabled: true
    filter: true

bezkoder:
  openapi:
    dev-url: http://localhost:8081
#    dev-url: http://168.119.132.22:8080
    prod-url: http://168.119.132.18:8080

  app:
    jwtCookieName: bezkoder
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000

schemes:
  - https

server:
  port: 8081



# http://localhost:8081/swagger-ui/index.html#


